// Auto-generated by convert-planning.ts — DO NOT EDIT MANUALLY
import type { DayTemplate } from "../../types";

import { mk_j1 } from "./mk-j1";
import { hs_j2 } from "./hs-j2";
import { epcot_j3 } from "./epcot-j3";
import { mk_j4a } from "./mk-j4a";
import { epcot_j4b } from "./epcot-j4b";
import { hs_j4c } from "./hs-j4c";
import { universal_j5 } from "./universal-j5";
import { epic_j6 } from "./epic-j6";
import { ak_epic_j7 } from "./ak-epic-j7";

export const ALL_TEMPLATES: Record<string, DayTemplate> = {
  "mk-j1": mk_j1,
  "hs-j2": hs_j2,
  "epcot-j3": epcot_j3,
  "mk-j4a": mk_j4a,
  "epcot-j4b": epcot_j4b,
  "hs-j4c": hs_j4c,
  "universal-j5": universal_j5,
  "epic-j6": epic_j6,
  "ak-epic-j7": ak_epic_j7,
};

export function getTemplate(id: string): DayTemplate | null {
  return ALL_TEMPLATES[id] ?? null;
}
