// Auto-generated by convert-planning.ts — DO NOT EDIT MANUALLY
import type { ParkAlert } from "../types";

export const PARK_ALERTS: ParkAlert[] = [
  {
    "type": "closure",
    "park": "mk",
    "attraction": "Big Thunder Mountain",
    "message": "CLOSED until early May 2026",
    "severity": "critical"
  },
  {
    "type": "closure",
    "park": "hs",
    "attraction": "Rock'n'Roller Coaster",
    "message": "CLOSED for Muppets retheme",
    "severity": "critical"
  },
  {
    "type": "closure",
    "park": "ak",
    "attraction": "DINOSAUR",
    "message": "Permanently CLOSED (Feb 2026)",
    "severity": "critical"
  },
  {
    "type": "closure",
    "park": "ak",
    "attraction": "Conservation Station",
    "message": "CLOSED until May 26, 2026",
    "severity": "critical"
  },
  {
    "type": "rule",
    "park": "epic",
    "attraction": "️ Stardust Racers",
    "message": "52\" = 132 cm — CHECK!",
    "severity": "warning"
  },
  {
    "type": "rule",
    "park": "ioa",
    "attraction": "️ VelociCoaster",
    "message": "51\" = 130 cm — CHECK!",
    "severity": "warning"
  },
  {
    "type": "rule",
    "park": "epic",
    "attraction": "️ Monsters Unchained",
    "message": "48\" = 122 cm",
    "severity": "warning"
  },
  {
    "type": "rule",
    "park": "epic",
    "attraction": "️ Dragon Racer's Rally",
    "message": "48\" = 122 cm",
    "severity": "warning"
  }
];
