// Auto-generated by convert-planning.ts — DO NOT EDIT MANUALLY
import type { LLPurchase } from "../types";

export const LL_CALENDAR: LLPurchase[] = [
  {
    "purchaseDate": "11 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Magic Kingdom",
    "park": "Magic Kingdom",
    "product": "MP : Peter Pan + Haunted Mansion + Pirates",
    "type": "multi_pass",
    "cost": "$148"
  },
  {
    "purchaseDate": "12 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Hollywood Studios",
    "park": "Hollywood Studios",
    "product": "MP : Slinky Dog + Tower of Terror + Toy Story Mania!",
    "type": "multi_pass",
    "cost": "$128"
  },
  {
    "purchaseDate": "13 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "EPCOT",
    "park": "EPCOT",
    "product": "MP : Frozen Ever After + Soarin' + Spaceship Earth",
    "type": "multi_pass",
    "cost": "$104"
  },
  {
    "purchaseDate": "14 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Magic Kingdom",
    "park": "Magic Kingdom",
    "product": "MP : Space Mountain + 2×T2",
    "type": "multi_pass",
    "cost": "$148"
  },
  {
    "purchaseDate": "14 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Magic Kingdom",
    "park": "Magic Kingdom",
    "product": "SP : TRON ($80) + Seven Dwarfs ($60)",
    "type": "single_pass",
    "cost": "$140",
    "priority": "PRIORITÉ"
  },
  {
    "purchaseDate": "15 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Hollywood Studios",
    "park": "Hollywood Studios",
    "product": "SP : Rise of the Resistance",
    "type": "single_pass",
    "cost": "$88"
  },
  {
    "purchaseDate": "16 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "EPCOT",
    "park": "EPCOT",
    "product": "SP : Guardians of the Galaxy",
    "type": "single_pass",
    "cost": "$84"
  },
  {
    "purchaseDate": "17 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Animal Kingdom",
    "park": "Animal Kingdom",
    "product": "MP : Na'vi River + Kilimanjaro + Everest",
    "type": "multi_pass",
    "cost": "$88"
  },
  {
    "purchaseDate": "20 avril",
    "purchaseTime": "7h00 EST",
    "parkDate": "Animal Kingdom",
    "park": "Animal Kingdom",
    "product": "SP : Flight of Passage",
    "type": "single_pass",
    "cost": "$72"
  }
];
