// Auto-generated by convert-planning.ts — DO NOT EDIT MANUALLY
import type { MustSeeItem } from "../types";

export const MUST_SEE: MustSeeItem[] = [
  {
    "name": "TRON Lightcycle / Run",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1",
      "J4-A"
    ]
  },
  {
    "name": "Seven Dwarfs Mine Train",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1",
      "J4-A"
    ]
  },
  {
    "name": "Haunted Mansion",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1",
      "J4-A"
    ]
  },
  {
    "name": "Space Mountain",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1",
      "J4-A"
    ]
  },
  {
    "name": "Pirates of the Caribbean",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1",
      "J4-A"
    ]
  },
  {
    "name": "Tiana's Bayou Adventure",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1"
    ]
  },
  {
    "name": "Jungle Cruise",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1"
    ]
  },
  {
    "name": "Peter Pan's Flight",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J1",
      "J4-A"
    ]
  },
  {
    "name": "Buzz Lightyear",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J1"
    ]
  },
  {
    "name": "It's a Small World",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J1"
    ]
  },
  {
    "name": "PhilharMagic",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J1"
    ]
  },
  {
    "name": "PeopleMover (TTA)",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-A"
    ]
  },
  {
    "name": "Meet Mickey",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-A"
    ]
  },
  {
    "name": "Happily Ever After",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J1 (21h30)"
    ]
  },
  {
    "name": "Disney Starlight Parade",
    "park": "mk",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J1 (20h30)"
    ]
  },
  {
    "name": "Festival of Fantasy Parade",
    "park": "mk",
    "priority": "must-do",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "→ J4-A à ~15h00 (seule représentation). Insérer entre Goûter Aloha (15:35) et PeopleMover (16:10). Visionner depuis Frontierland."
  },
  {
    "name": "Rise of the Resistance",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2",
      "J4-C"
    ]
  },
  {
    "name": "Slinky Dog Dash",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2",
      "J4-C"
    ]
  },
  {
    "name": "Tower of Terror",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2 (×2)",
      "J4-C"
    ]
  },
  {
    "name": "Toy Story Mania!",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2",
      "J4-C"
    ]
  },
  {
    "name": "Smugglers Run",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2",
      "J4-C"
    ]
  },
  {
    "name": "Mickey & Minnie's Runaway Railway",
    "park": "hs",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J2"
    ]
  },
  {
    "name": "Star Tours",
    "park": "hs",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J2"
    ]
  },
  {
    "name": "Fantasmic!",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2 (20h30)"
    ]
  },
  {
    "name": "Indiana Jones Stunt Spectacular",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2 (11h20)"
    ]
  },
  {
    "name": "The Little Mermaid Musical",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J4-C"
    ]
  },
  {
    "name": "Galaxy's Edge Immersion",
    "park": "hs",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J2",
      "J4-C"
    ]
  },
  {
    "name": "Savi's Workshop",
    "park": "hs",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-C"
    ]
  },
  {
    "name": "Oga's Cantina",
    "park": "hs",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-C"
    ]
  },
  {
    "name": "MuppetVision 3D",
    "park": "hs",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-C"
    ]
  },
  {
    "name": "Frozen Sing-Along",
    "park": "hs",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-C"
    ]
  },
  {
    "name": "Guardians of the Galaxy",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Remy's Ratatouille",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Soarin'",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Test Track",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Frozen Ever After",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Spaceship Earth",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3"
    ]
  },
  {
    "name": "Journey of Water (Moana)",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-B"
    ]
  },
  {
    "name": "Living with the Land",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J3"
    ]
  },
  {
    "name": "Gran Fiesta Tour",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J3"
    ]
  },
  {
    "name": "The Seas with Nemo",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Figment",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-B"
    ]
  },
  {
    "name": "Turtle Talk with Crush",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-B"
    ]
  },
  {
    "name": "Club Cool",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J4-B"
    ]
  },
  {
    "name": "American Adventure",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J3"
    ]
  },
  {
    "name": "Luminous",
    "park": "epcot",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J3 (21h)"
    ]
  },
  {
    "name": "Butterfly Landing",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J3"
    ]
  },
  {
    "name": "Outdoor Kitchens (F&G)",
    "park": "epcot",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J3",
      "J4-B"
    ]
  },
  {
    "name": "Hagrid's Magical Creatures",
    "park": "ioa",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "VelociCoaster",
    "park": "ioa",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Forbidden Journey",
    "park": "ioa",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Incredible Hulk Coaster",
    "park": "ioa",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Spider-Man",
    "park": "ioa",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Flight of the Hippogriff",
    "park": "ioa",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Escape from Gringotts",
    "park": "usf",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Revenge of the Mummy",
    "park": "usf",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Transformers",
    "park": "usf",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Minion Mayhem",
    "park": "usf",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Villain-Con Minion Blast",
    "park": "usf",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "CineSational",
    "park": "usf",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5 (21h)"
    ]
  },
  {
    "name": "Hogwarts Always",
    "park": "ioa",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5 (21h50)"
    ]
  },
  {
    "name": "Hogwarts Express",
    "park": "ioa↔usf",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5 (×2)"
    ]
  },
  {
    "name": "Hogsmeade + Diagon Alley",
    "park": "ioa+usf",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J5"
    ]
  },
  {
    "name": "Battle at the Ministry",
    "park": "epic",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Monsters Unchained",
    "park": "epic",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Mario Kart: Bowser's Challenge",
    "park": "epic",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Stardust Racers",
    "park": "epic",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Hiccup's Wing Gliders",
    "park": "epic",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J6",
      "J7"
    ]
  },
  {
    "name": "Dragon Racer's Rally",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6",
      "J7"
    ]
  },
  {
    "name": "Mine-Cart Madness",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Fyre Drill",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6",
      "J7"
    ]
  },
  {
    "name": "Yoshi's Adventure",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Curse of the Werewolf",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Le Cirque Arcanus",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Power-Up Band",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J6"
    ]
  },
  {
    "name": "Starfall Spectacle",
    "park": "epic",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J6 (21h20)"
    ]
  },
  {
    "name": "The Untrainable Dragon",
    "park": "epic",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "→ J7 PM Epic (19h20-20h40 Isle of Berk). Insérer show 20 min pendant segment sunset Isle of Berk. Horaires à vérifier sur place."
  },
  {
    "name": "Flight of Passage",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J7 (rope drop)"
    ]
  },
  {
    "name": "Na'vi River Journey",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J7"
    ]
  },
  {
    "name": "Kilimanjaro Safaris",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J7"
    ]
  },
  {
    "name": "Expedition Everest",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J7"
    ]
  },
  {
    "name": "Kali River Rapids",
    "park": "ak",
    "priority": "recommended",
    "isPlanned": true,
    "plannedDays": [
      "J7"
    ]
  },
  {
    "name": "Festival of the Lion King",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": true,
    "plannedDays": [
      "J7 (11h)"
    ]
  },
  {
    "name": "Zootopia: Better Zoogether!",
    "park": "ak",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "→ J7 AK à 12:30 (après Kali, avant déjeuner). Show 3D ~20 min à Discovery Island. Remplace It's Tough to be a Bug."
  },
  {
    "name": "Maharajah Jungle Trek",
    "park": "ak",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "→ J7 AK : intégrer 15 min après Everest (12:00). Trail self-guided en zone Asia, sans file d'attente."
  },
  {
    "name": "Gorilla Falls Trail",
    "park": "ak",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "→ J7 AK : intégrer 15 min après Safaris (10:50). Trail self-guided en zone Africa, sortie Safaris directe."
  },
  {
    "name": "Tree of Life Awakenings",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "Projection NOCTURNE → impossible car départ AK à 13h30. Alternative : admirer le Tree of Life de jour à Discovery Island (12:55)."
  },
  {
    "name": "Pandora at Night",
    "park": "ak",
    "priority": "must-do",
    "isPlanned": false,
    "plannedDays": [
      "—"
    ],
    "suggestion": "Bioluminescence NOCTURNE → impossible car départ AK à 13h30. Pandora reste spectaculaire de jour."
  },
  {
    "name": "SYNTHÈSE DES PROPOSITIONS DE CRÉNEAUX",
    "park": "",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "Activité",
    "park": "jour / parc",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "Festival of Fantasy Parade",
    "park": "j4-a (mk)",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "The Untrainable Dragon",
    "park": "j7 pm (epic)",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "Zootopia: Better Zoogether!",
    "park": "j7 (ak)",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "Maharajah Jungle Trek",
    "park": "j7 (ak)",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "Gorilla Falls Trail",
    "park": "j7 (ak)",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  },
  {
    "name": "SCORE GLOBAL : 72 must-see référencés | 67 planifiés ✅ (93%) | 5 propositions d'ajout ❌ | 2 impossibles structurels ⚠️",
    "park": "",
    "priority": "recommended",
    "isPlanned": false,
    "plannedDays": []
  }
];
