// Auto-generated by convert-planning.ts — DO NOT EDIT MANUALLY
import type { TripDay } from "../types";

export const TRIP_DAYS: TripDay[] = [
  { date: "2026-04-12", dayIndex: 1, templates: [], activeTemplateId: "", isMultiPark: false },
  { date: "2026-04-13", dayIndex: 2, templates: [], activeTemplateId: "", isMultiPark: false },
  { date: "2026-04-14", dayIndex: 3, templates: ["mk-j1"], activeTemplateId: "mk-j1", isMultiPark: false },
  { date: "2026-04-15", dayIndex: 4, templates: ["hs-j2"], activeTemplateId: "hs-j2", isMultiPark: false },
  { date: "2026-04-16", dayIndex: 5, templates: ["epcot-j3"], activeTemplateId: "epcot-j3", isMultiPark: false },
  {
    date: "2026-04-17", dayIndex: 6, templates: ["mk-j4a"], activeTemplateId: "mk-j4a", isMultiPark: false,
    alternatives: [
      { templateId: "mk-j4a", label: "MK (Bonus : nouveautés + re-rides)", reason: "Winnie, Dumbo, Meet Mickey, PeopleMover + re-rides coasters!" },
      { templateId: "epcot-j4b", label: "EPCOT (compléments J3)", reason: "Journey of Water (Moana), Figment, Nemo, Club Cool + World Showcase!" },
      { templateId: "hs-j4c", label: "HS (compléments J2)", reason: "Little Mermaid Musical, Savi's Workshop, Oga's Cantina + immersion Star Wars!" },
    ],
  },
  { date: "2026-04-18", dayIndex: 7, templates: ["universal-j5"], activeTemplateId: "universal-j5", isMultiPark: true },
  { date: "2026-04-19", dayIndex: 8, templates: ["epic-j6"], activeTemplateId: "epic-j6", isMultiPark: false },
  { date: "2026-04-20", dayIndex: 9, templates: ["ak-epic-j7"], activeTemplateId: "ak-epic-j7", isMultiPark: true },
  { date: "2026-04-21", dayIndex: 10, templates: [], activeTemplateId: "", isMultiPark: false },
  { date: "2026-04-22", dayIndex: 11, templates: [], activeTemplateId: "", isMultiPark: false },
];
